apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: gorizond
  namespace: tidb-cluster
spec:
  version: v8.5.0
  timezone: UTC
  pvReclaimPolicy: Retain
  enableDynamicConfiguration: true
  configUpdateStrategy: RollingUpdate
  discovery: {}
  helper:
    image: alpine:3.16.0
  pd:
    baseImage: pingcap/pd
    maxFailoverCount: 0
    replicas: 1
    limits:
      cpu: '2'
      memory: 128Mi
    requests:
      cpu: '0.05'
      memory: 128Mi
    requests:
      storage: "1Gi"
    config: ''
  tikv:
    baseImage: pingcap/tikv
    maxFailoverCount: 0
    evictLeaderTimeout: 1m
    replicas: 1
    limits:
      cpu: '2'
      memory: 128Mi
    requests:
      cpu: '0.05'
      memory: 128Mi
    requests:
      storage: "5Gi"
    config: |
      [raftdb]
        max-open-files = 256

      [rocksdb]
        max-open-files = 256
        max-total-wal-size = "200MB"
        max-sub-compactions = 3
        
      [storage]
        reserve-space = "200MB"
  tidb:
    baseImage: pingcap/tidb
    maxFailoverCount: 0
    replicas: 1
    limits:
      cpu: '2'
      memory: 128Mi
    requests:
      cpu: '0.05'
      memory: 128Mi
    service:
      type: ClusterIP
    config: |
      [log]
        [log.file]
          max-backups = 3
