apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: gorizond
  namespace: tidb-cluster
spec:
  version: v8.5.0
  timezone: UTC
  pvReclaimPolicy: Retain
  enableDynamicConfiguration: true
  configUpdateStrategy: RollingUpdate
  discovery: {}
  helper:
    image: alpine:3.16.0
  pd:
    baseImage: pingcap/pd
    maxFailoverCount: 0
    replicas: 1
    limits:
      cpu: '2'
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 256Mi
      storage: 1Gi
    config: ''
  tikv:
    baseImage: pingcap/tikv
    maxFailoverCount: 0
    evictLeaderTimeout: 1m
    replicas: 3
    limits:
      cpu: '2'
      memory: 2560Mi
    requests:
      cpu: 50m
      memory: 2560Mi
      storage: 10Gi
    config: |
      [raft-engine]
        purge-interval = "10m"
        purge-threshold = "1GB"

      [raftdb]
        max-open-files = 256

      [rocksdb]
        max-open-files = 256
        max-sub-compactions = 3
        max-total-wal-size = "200MB"
        [rocksdb.defaultcf]
          write-buffer-size = "16MB"
        [rocksdb.writecf]
          write-buffer-size = "16MB"

      [server]
        grpc-memory-pool-quota = "256MB"

      [storage]
        reserve-space = "200MB"
        [storage.block-cache]
          capacity = "64MB"
  tidb:
    baseImage: pingcap/tidb
    maxFailoverCount: 0
    replicas: 1
    limits:
      cpu: '2'
      memory: 1536Mi
    requests:
      cpu: 50m
      memory: 1536Mi
    service:
      type: ClusterIP
    config: |
      [log]
        [log.file]
          max-backups = 3
