apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: gorizond
  namespace: tidb-cluster
spec:
  imagePullPolicy: IfNotPresent
  pd:
    baseImage: pingcap/pd
    replicas: 1
    requests:
      storage: 1Gi
  tidb:
    baseImage: pingcap/tidb
    replicas: 1
    service:
      type: ClusterIP
  tikv:
    baseImage: pingcap/tikv
    replicas: 1
    requests:
      storage: 1Gi
  timezone: UTC